### ISSUE TITLE
erofs when install nodejs?

### ISSUE THREAD

**Issue by kvmpret** [onlurking/termux#3]
[ termux ] configs found, overwrite? [Y/n] n
[ npm ] configuring prefix
Error: EROFS: read-only file system, mkdir '/usr'
TypeError: Cannot read property 'loaded' of undefined
    at exit (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at errorHandler (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at /data/data/com.termux/files/usr/lib/node_modules/npm/bin/npm-cli.js:77:20
    at cb (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/npm.js:225:22)
    at /data/data/com.termux/files/usr/lib/node_modules/npm/lib/npm.js:263:24
    at /data/data/com.termux/files/usr/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /data/data/com.termux/files/usr/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/config/core.js:173:20)
/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/error-handler.js:98
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/error-handler.js:98:27)
    at process.errorHandler (/data/data/com.termux/files/usr/lib/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:200:13)
    at process._fatalException (internal/process/execution.js:146:25)
[ yarn ] install yarn? (recommended) [Y/n] y

**Comment by onlurking** [comment]
Can you do this commands @kvmpret and tell me if this fix the problem?
```bash
rm ~/.termux -rf
apt update && apt upgrade
apt purge nodejs npm
curl -fsSL https://git.io/termux | bash -s -- --nodejs
```

**Comment by kvmpret** [comment]
yes, thank you
